version: 2

jobs:
  python:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install --user --requirement requirements.txt --requirement test_requirements.txt
      - run: python setup.py lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - python

notify:
  webhooks:
    - url: https://bot.suddi.io/hooks/circle
